---
- hosts: localhost
  tasks:
    - name: "Create .ssh directory"
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: 0755
      register: path_ssh
      

    - name: "Generate ssh key"
      openssh_keypair:
        path: "{{ item.path }}"
      with_items:
        - "{{ path_ssh.files }}"
