---
- hosts: localhost
  tasks:
    - name: "Create .ssh directory"
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: 0755
      register: __path_ssh

    - name: Debug variable
      debug:
        var: __path_ssh

    - name: "Generate ssh key"
      openssh_keypair:
        path: "{{ item.path }}/id_rsa"
      with_items:
        - "{{ __path_ssh }}"

    - name: "Create authorized_keys"
      copy:
        src: "{{ item.path }}/id_rsa.pub"
        dest: "{{ item.path }}/authorized_keys"
        owner: root
        group: root
        mode: 0644
      with_items:
        - "{{ __path_ssh }}"

    - name: "Copy ssh key"
      shell: |
        for i in $(sed '1d;$d' /etc/ansible/inventory)
        do 
          scp -o StrictHostKeyChecking=no ~/.ssh/authorized_keys root@${i}:~/.ssh/authorized_keys
          ssh-copy-id -i ~/.ssh/id_rsa.pub root@${i}
        done
