---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /etc/ansible/password_root.yml
  tasks:
    - name: "Create .ssh directory"
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: 0755
      register: __path_ssh

    - name: "Generate ssh key"
      openssh_keypair:
        path: "{{ item.path }}/id_rsa"
      with_items:
        - "{{ __path_ssh }}"

    - name: "Create authorized_keys"
      copy:
        src: "{{ item.path }}/id_rsa.pub"
        dest: "{{ item.path }}/authorized_keys"
        owner: root
        group: root
        mode: 0644
      with_items:
        - "{{ __path_ssh }}"

    - name: "Copy ssh key"
      shell: |
        for i in $(cat /etc/ansible/list_server.txt)
        do 
          sshpass -p "{{ root_password }}" scp -o StrictHostKeyChecking=no ~/.ssh/authorized_keys root@${i}:~/.ssh/authorized_keys
          sshpass -p "{{ root_password }}" ssh-copy-id -i ~/.ssh/id_rsa.pub root@${i}
        done

- hosts: all
  gather_facts: false
  tasks:
    - name: "Ping machine"
      ping: