---
- hosts: all
  tasks:
    - name: "Set fact"
      set_fact:
        h_a_p: "{{ ansible_host }} : {{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

    - name: "test gen password"
      debug:
        msg: "{{ h_a_p }}"

    - name:
      add_host:
        name: "TEST_ADD_HOST"
        secret: "{{ h_a_p }}"

    - name:
      debug:
        msg: "{{ hostvars['TEST_ADD_HOST']['secret'] }}"
