---
- hosts: all
#  vars:
#    pvfe: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
#    h_a_p: "{{ ansible_host }} : {{ pvfe }}"
  tasks:
    - name: "Set fact 1"
      set_fact:
        Password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

    - name: "Set fact 2"
      set_fact:
        h_a_p: "{{ ansible_host }} : {{ Password }}"
      with_items: "{{ ansible_play_hosts }}"


    - name: "Unique password"
      debug:
        msg: "{{ Password }}"

    - name: "All password"
      debug:
        msg: "{{ h_a_p }}"

#   - name: "copie fichier test"
#     copy: 
#       src: /etc/ansible/fic_test_mdp.txt
#       dest: /root/fic_test_mdp.txt
#       owner: root
#       group: root
#       mode: 0775

#    - name: "replace password"
#      replace:
#        path: /root/fic_test_mdp.txt
#        after: '    <user username="vfe" password='
#        before: ' roles="vfe_front"/>'
#        regexp: '"vfe"'
#        replace: '"{{ pvfe }}"'
#        backup: yes
